apiVersion: v1
kind: Secret
metadata:
  name: kube-controller-manager
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  ca.crt: {{ pki "combined-ca.crt" }}
  service-account: {{ pki "service-account-key.pem" }}
  config.yaml: {{ base64 "kube-controller-manager/config.yaml" }}
  cluster-signer.crt: {{ pki "cluster-signer.crt" }}
  cluster-signer.key: {{ pki "cluster-signer.key" }}
