apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
spec:
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
    nodePort: {{ .APINodePort }}
  selector:
    app: kube-apiserver
  type: NodePort
