apiVersion: v1
kind: Secret
metadata:
  name: openvpn-client
data:
  tls.crt: {{ pki "openvpn-kube-apiserver-client.crt" }}
  tls.key: {{ pki "openvpn-kube-apiserver-client.key" }}
  ca.crt: {{ pki "openvpn-ca.crt" }}
  client.conf: {{ base64 "kube-apiserver/client.conf" }}
