kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-scheduler
spec:
  replicas: {{ .Replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kube-scheduler
  template:
    metadata:
      labels:
        app: kube-scheduler
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["kube-scheduler"]
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      automountServiceAccountToken: false
      containers:
      - name: kube-scheduler
        image: {{ imageFor "hyperkube" }}
        command:
        - hyperkube
        - kube-scheduler
        args:
        - "--config=/etc/kubernetes/config/config.yaml"
        - "--cert-dir=/var/run/kubernetes"
        - "--port=0"
        - "--authentication-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--authorization-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "-v=2"
{{ if .KubeSchedulerResources }}
        resources:{{ range .KubeSchedulerResources }}{{ range .Requests }}
          requests:
            cpu: {{ .CPU }}
            memory: {{ .Memory }}{{ end }}{{ range .Limits }}
          limits:
            cpu: {{ .CPU }}
            memory: {{ .Memory }}{{ end }}{{ end }}
{{ end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/config
          name: config
        - mountPath: /var/run/kubernetes/
          name: cert
        workDir: /var/run/kubernetes
      volumes:
      - secret:
          secretName: service-network-admin-kubeconfig
        name: secret
      - configMap:
          name: kube-scheduler-config
        name: config
      - emptyDir: {}
        name: cert
