apiVersion: v1
kind: Secret
metadata:
  name: openshift-apiserver
data:
  aggregator-client-ca.crt: {{ pki "root-ca.crt" }}
  etcd-ca.crt: {{ pki "root-ca.crt" }}
  serving-ca.crt: {{ pki "root-ca.crt" }}
