---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ .APIService }}
spec:
  caBundle: {{ pki "root-ca.crt" }}
  group: {{ .APIServiceGroup }}
  groupPriorityMinimum: 9900
  service:
    name: openshift-apiserver
    namespace: default
  version: v1
  versionPriority: 15
