---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ .APIService }}
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
spec:
  group: {{ .APIServiceGroup }}
  groupPriorityMinimum: 9900
  service:
    name: openshift-apiserver
    namespace: default
  version: v1
  versionPriority: 15
