apiVersion: v1
kind: Pod
metadata:
  name: auto-approver
spec:
  tolerations:
    - key: "multi-az-worker"
      operator: "Equal"
      value: "true"
      effect: NoSchedule
  containers:
  - image: {{ imageFor "cli" }}
    env:
    - name: KUBECONFIG
      value: /etc/openshift/kubeconfig/kubeconfig
    imagePullPolicy: IfNotPresent
    name: autoapprover
    command:
    - /bin/bash
    args:
    - -c
    - |-
      #!/bin/bash
      set -eu
      while true; do
         if oc get csr | grep Pending; then
            oc get csr | grep Pending | awk '{ print $1 }' | xargs oc adm certificate approve
         fi
         sleep 10
      done
{{ if .AutoApproverResources }}
        resources:{{ range .AutoApproverResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
    volumeMounts:
    - mountPath: /etc/openshift/kubeconfig
      name: kubeconfig
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: kubeconfig
    secret:
      secretName: service-network-admin-kubeconfig
