apiVersion: v1
kind: Service
metadata:
  name: openvpn-server
spec:
  ports:
  - port: 1194
    protocol: UDP
    targetPort: 1194
    nodePort: ${OPENVPN_NODEPORT}
  selector:
    app: openvpn-server
  type: NodePort
