apiVersion: v1
kind: Secret
metadata:
  name: openshift-controller-manager
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  server.crt: {{ pki "openshift-controller-manager-server.crt" }}
  server.key: {{ pki "openshift-controller-manager-server.key" }}
  ca.crt: {{ pki "root-ca.crt" }}
  config.yaml: {{ base64 "openshift-controller-manager/config.yaml" }}
